### ISSUE TITLE
New direct provider (weather station)

### ISSUE THREAD

**Issue by gereic** [winds-mobi/winds-mobi-providers#61]
Hi, I'm the developer of GXAircom ground-stations.
Is it possible to send weather-station-data directly from weatherstation to winds.mobi?
Or do I have to setup a server, where the weather-stations sends the data and create a provider, which collects the data from the server.

**Comment by ysavary** [comment]
Hi @gereic,

For now, you have to create PR [winds.mobi provider](https://github.com/winds-mobi/winds-mobi-providers#add-a-new-provider-to-windsmobi) that reads data from your server.

**Comment by ysavary** [comment]
Hi @gereic,

I improved the Dockerfile and updated the README to make the development of a new provider easier with Docker.

> Is all in the docker, or is the docker only for database and so on ?

With the docker compose profile `scheduler`, you can build and run the providers with docker. You can also run only one (new) provider with docker: https://github.com/winds-mobi/winds-mobi-providers/blob/main/README.md#and-test-it 

> which system is best for developing ? (linux or windows)

I'm working on MacOS but it should work on Linux and Windows.

**Comment by gereic** [comment]
Hi @ysavary,

when I do "docker compose up" I get the following error:
[+] Running 3/3
 ✔ Network winds-mobi-providers              Created                                                                                                                                                                    0.1s
 ✔ Container winds-mobi-providers-mongodb-1  Created                                                                                                                                                                    0.3s
 ✔ Container winds-mobi-providers-redis-1    Created                                                                                                                                                                    0.3s
Attaching to winds-mobi-providers-mongodb-1, winds-mobi-providers-redis-1
winds-mobi-providers-redis-1    | 1:C 19 May 2023 15:59:33.993 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
winds-mobi-providers-redis-1    | 1:C 19 May 2023 15:59:34.000 # Redis version=7.0.4, bits=64, commit=00000000, modified=0, pid=1, just started
winds-mobi-providers-redis-1    | 1:C 19 May 2023 15:59:34.000 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
winds-mobi-providers-redis-1    | 1:M 19 May 2023 15:59:34.019 * monotonic clock: POSIX clock_gettime
winds-mobi-providers-redis-1    | 1:M 19 May 2023 15:59:34.020 * Running mode=standalone, port=6379.
winds-mobi-providers-redis-1    | 1:M 19 May 2023 15:59:34.020 # Server initialized
winds-mobi-providers-redis-1    | 1:M 19 May 2023 15:59:34.020 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
winds-mobi-providers-redis-1    | 1:M 19 May 2023 15:59:34.021 * Ready to accept connections
winds-mobi-providers-mongodb-1  | {"t":{"$date":"2023-05-19T15:59:34.066+00:00"},"s":"I",  "c":"CONTROL",  "id":23285,   "ctx":"main","msg":"Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'"}
winds-mobi-providers-mongodb-1  | {"t":{"$date":"2023-05-19T15:59:34.069+00:00"},"s":"I",  "c":"NETWORK",  "id":4648601, "ctx":"main","msg":"Implicit TCP FastOpen unavailable. If TCP FastOpen is required, set tcpFastOpenServer, tcpFastOpenClient, and tcpFastOpenQueueSize."}
winds-mobi-providers-mongodb-1  | {"t":{"$date":"2023-05-19T15:59:34.070+00:00"},"s":"I",  "c":"STORAGE",  "id":4615611, "ctx":"initandlisten","msg":"MongoDB starting","attr":{"pid":1,"port":27017,"dbPath":"/data/db","architecture":"64-bit","host":"eb1364a2c10e"}}
winds-mobi-providers-mongodb-1  | {"t":{"$date":"2023-05-19T15:59:34.070+00:00"},"s":"I",  "c":"CONTROL",  "id":23403,   "ctx":"initandlisten","msg":"Build Info","attr":{"buildInfo":{"version":"4.4.19","gitVersion":"9a996e0ad993148b9650dc402e6d3b1804ad3b8a","openSSLVersion":"OpenSSL 1.1.1f  31 Mar 2020","modules":[],"allocator":"tcmalloc","environment":{"distmod":"ubuntu2004","distarch":"x86_64","target_arch":"x86_64"}}}}
winds-mobi-providers-mongodb-1  | {"t":{"$date":"2023-05-19T15:59:34.070+00:00"},"s":"I",  "c":"CONTROL",  "id":51765,   "ctx":"initandlisten","msg":"Operating System","attr":{"os":{"name":"Ubuntu","version":"20.04"}}}
winds-mobi-providers-mongodb-1  | {"t":{"$date":"2023-05-19T15:59:34.070+00:00"},"s":"I",  "c":"CONTROL",  "id":21951,   "ctx":"initandlisten","msg":"Options set by command line","attr":{"options":{"net":{"bindIp":"*"}}}}
winds-mobi-providers-mongodb-1  | {"t":{"$date":"2023-05-19T15:59:34.076+00:00"},"s":"I",  "c":"STORAGE",  "id":22315,   "ctx":"initandlisten","msg":"Opening WiredTiger","attr":{"config":"create,cache_size=5821M,session_max=33000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000,close_scan_interval=10,close_handle_minimum=250),statistics_log=(wait=0),verbose=[recovery_progress,checkpoint_progress,compact_progress],"}}
winds-mobi-providers-mongodb-1  | {"t":{"$date":"2023-05-19T15:59:34.702+00:00"},"s":"E",  "c":"STORAGE",  "id":22435,   "ctx":"initandlisten","msg":"WiredTiger error","attr":{"error":17,"message":"[1684511974:702029][1:0x7f048a68dcc0], connection: __posix_open_file, 808: /data/db/WiredTiger.wt: handle-open: open: File exists"}}
winds-mobi-providers-mongodb-1  | {"t":{"$date":"2023-05-19T15:59:34.714+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"initandlisten","msg":"WiredTiger message","attr":{"message":"unexpected file WiredTiger.wt found, renamed to WiredTiger.wt.12"}}
winds-mobi-providers-mongodb-1  | {"t":{"$date":"2023-05-19T15:59:34.732+00:00"},"s":"E",  "c":"STORAGE",  "id":22435,   "ctx":"initandlisten","msg":"WiredTiger error","attr":{"error":1,"message":"[1684511974:732855][1:0x7f048a68dcc0], connection: __posix_open_file, 808: /data/db/WiredTiger.wt: handle-open: open: Operation not permitted"}}
winds-mobi-providers-mongodb-1  | {"t":{"$date":"2023-05-19T15:59:34.807+00:00"},"s":"E",  "c":"STORAGE",  "id":22435,   "ctx":"initandlisten","msg":"WiredTiger error","attr":{"error":17,"message":"[1684511974:807036][1:0x7f048a68dcc0], connection: __posix_open_file, 808: /data/db/WiredTiger.wt: handle-open: open: File exists"}}
winds-mobi-providers-mongodb-1  | {"t":{"$date":"2023-05-19T15:59:34.817+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"initandlisten","msg":"WiredTiger message","attr":{"message":"unexpected file WiredTiger.wt found, renamed to WiredTiger.wt.13"}}
winds-mobi-providers-mongodb-1  | {"t":{"$date":"2023-05-19T15:59:34.819+00:00"},"s":"E",  "c":"STORAGE",  "id":22435,   "ctx":"initandlisten","msg":"WiredTiger error","attr":{"error":1,"message":"[1684511974:819810][1:0x7f048a68dcc0], connection: __posix_open_file, 808: /data/db/WiredTiger.wt: handle-open: open: Operation not permitted"}}
winds-mobi-providers-mongodb-1  | {"t":{"$date":"2023-05-19T15:59:34.880+00:00"},"s":"E",  "c":"STORAGE",  "id":22435,   "ctx":"initandlisten","msg":"WiredTiger error","attr":{"error":17,"message":"[1684511974:880652][1:0x7f048a68dcc0], connection: __posix_open_file, 808: /data/db/WiredTiger.wt: handle-open: open: File exists"}}
winds-mobi-providers-mongodb-1  | {"t":{"$date":"2023-05-19T15:59:34.898+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"initandlisten","msg":"WiredTiger message","attr":{"message":"unexpected file WiredTiger.wt found, renamed to WiredTiger.wt.14"}}
winds-mobi-providers-mongodb-1  | {"t":{"$date":"2023-05-19T15:59:34.902+00:00"},"s":"E",  "c":"STORAGE",  "id":22435,   "ctx":"initandlisten","msg":"WiredTiger error","attr":{"error":1,"message":"[1684511974:902793][1:0x7f048a68dcc0], connection: __posix_open_file, 808: /data/db/WiredTiger.wt: handle-open: open: Operation not permitted"}}
winds-mobi-providers-mongodb-1  | {"t":{"$date":"2023-05-19T15:59:34.906+00:00"},"s":"W",  "c":"STORAGE",  "id":22347,   "ctx":"initandlisten","msg":"Failed to start up WiredTiger under any compatibility version. This may be due to an unsupported upgrade or downgrade."}
winds-mobi-providers-mongodb-1  | {"t":{"$date":"2023-05-19T15:59:34.906+00:00"},"s":"F",  "c":"STORAGE",  "id":28595,   "ctx":"initandlisten","msg":"Terminating.","attr":{"reason":"1: Operation not permitted"}}
winds-mobi-providers-mongodb-1  | {"t":{"$date":"2023-05-19T15:59:34.906+00:00"},"s":"F",  "c":"-",        "id":23091,   "ctx":"initandlisten","msg":"Fatal assertion","attr":{"msgid":28595,"file":"src/mongo/db/storage/wiredtiger/wiredtiger_kv_engine.cpp","line":958}}
winds-mobi-providers-mongodb-1  | {"t":{"$date":"2023-05-19T15:59:34.906+00:00"},"s":"F",  "c":"-",        "id":23092,   "ctx":"initandlisten","msg":"\n\n***aborting after fassert() failure\n\n"}
winds-mobi-providers-mongodb-1 exited with code 14

Any suggestions ?

**Comment by gereic** [comment]
@ysavary ,

I got the following error, when starting mongo-db.
Can you check, what is wrong ?

2023-05-25 17:06:45 {"t":{"$date":"2023-05-25T15:06:45.527+00:00"},"s":"I",  "c":"CONTROL",  "id":23285,   "ctx":"main","msg":"Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'"}
2023-05-25 17:06:45 {"t":{"$date":"2023-05-25T15:06:45.529+00:00"},"s":"I",  "c":"NETWORK",  "id":4648601, "ctx":"main","msg":"Implicit TCP FastOpen unavailable. If TCP FastOpen is required, set tcpFastOpenServer, tcpFastOpenClient, and tcpFastOpenQueueSize."}
2023-05-25 17:06:45 {"t":{"$date":"2023-05-25T15:06:45.530+00:00"},"s":"I",  "c":"STORAGE",  "id":4615611, "ctx":"initandlisten","msg":"MongoDB starting","attr":{"pid":1,"port":27017,"dbPath":"/data/db","architecture":"64-bit","host":"7d03dbad663a"}}
2023-05-25 17:06:45 {"t":{"$date":"2023-05-25T15:06:45.530+00:00"},"s":"I",  "c":"CONTROL",  "id":23403,   "ctx":"initandlisten","msg":"Build Info","attr":{"buildInfo":{"version":"4.4.19","gitVersion":"9a996e0ad993148b9650dc402e6d3b1804ad3b8a","openSSLVersion":"OpenSSL 1.1.1f  31 Mar 2020","modules":[],"allocator":"tcmalloc","environment":{"distmod":"ubuntu2004","distarch":"x86_64","target_arch":"x86_64"}}}}
2023-05-25 17:06:45 {"t":{"$date":"2023-05-25T15:06:45.530+00:00"},"s":"I",  "c":"CONTROL",  "id":51765,   "ctx":"initandlisten","msg":"Operating System","attr":{"os":{"name":"Ubuntu","version":"20.04"}}}
2023-05-25 17:06:45 {"t":{"$date":"2023-05-25T15:06:45.530+00:00"},"s":"I",  "c":"CONTROL",  "id":21951,   "ctx":"initandlisten","msg":"Options set by command line","attr":{"options":{"net":{"bindIp":"*"}}}}
2023-05-25 17:06:45 {"t":{"$date":"2023-05-25T15:06:45.545+00:00"},"s":"I",  "c":"STORAGE",  "id":22315,   "ctx":"initandlisten","msg":"Opening WiredTiger","attr":{"config":"create,cache_size=5821M,session_max=33000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000,close_scan_interval=10,close_handle_minimum=250),statistics_log=(wait=0),verbose=[recovery_progress,checkpoint_progress,compact_progress],"}}
2023-05-25 17:06:46 {"t":{"$date":"2023-05-25T15:06:46.628+00:00"},"s":"E",  "c":"STORAGE",  "id":22435,   "ctx":"initandlisten","msg":"WiredTiger error","attr":{"error":17,"message":"[1685027206:628671][1:0x7f90e318fcc0], connection: __posix_open_file, 808: /data/db/WiredTiger.wt: handle-open: open: File exists"}}
2023-05-25 17:06:46 {"t":{"$date":"2023-05-25T15:06:46.695+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"initandlisten","msg":"WiredTiger message","attr":{"message":"unexpected file WiredTiger.wt found, renamed to WiredTiger.wt.12"}}
2023-05-25 17:06:46 {"t":{"$date":"2023-05-25T15:06:46.702+00:00"},"s":"E",  "c":"STORAGE",  "id":22435,   "ctx":"initandlisten","msg":"WiredTiger error","attr":{"error":1,"message":"[1685027206:702182][1:0x7f90e318fcc0], connection: __posix_open_file, 808: /data/db/WiredTiger.wt: handle-open: open: Operation not permitted"}}
2023-05-25 17:06:46 {"t":{"$date":"2023-05-25T15:06:46.815+00:00"},"s":"E",  "c":"STORAGE",  "id":22435,   "ctx":"initandlisten","msg":"WiredTiger error","attr":{"error":17,"message":"[1685027206:815834][1:0x7f90e318fcc0], connection: __posix_open_file, 808: /data/db/WiredTiger.wt: handle-open: open: File exists"}}
2023-05-25 17:06:46 {"t":{"$date":"2023-05-25T15:06:46.829+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"initandlisten","msg":"WiredTiger message","attr":{"message":"unexpected file WiredTiger.wt found, renamed to WiredTiger.wt.13"}}
2023-05-25 17:06:46 {"t":{"$date":"2023-05-25T15:06:46.832+00:00"},"s":"E",  "c":"STORAGE",  "id":22435,   "ctx":"initandlisten","msg":"WiredTiger error","attr":{"error":1,"message":"[1685027206:832638][1:0x7f90e318fcc0], connection: __posix_open_file, 808: /data/db/WiredTiger.wt: handle-open: open: Operation not permitted"}}
2023-05-25 17:06:46 {"t":{"$date":"2023-05-25T15:06:46.895+00:00"},"s":"E",  "c":"STORAGE",  "id":22435,   "ctx":"initandlisten","msg":"WiredTiger error","attr":{"error":17,"message":"[1685027206:895037][1:0x7f90e318fcc0], connection: __posix_open_file, 808: /data/db/WiredTiger.wt: handle-open: open: File exists"}}
2023-05-25 17:06:46 {"t":{"$date":"2023-05-25T15:06:46.933+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"initandlisten","msg":"WiredTiger message","attr":{"message":"unexpected file WiredTiger.wt found, renamed to WiredTiger.wt.14"}}
2023-05-25 17:06:46 {"t":{"$date":"2023-05-25T15:06:46.939+00:00"},"s":"E",  "c":"STORAGE",  "id":22435,   "ctx":"initandlisten","msg":"WiredTiger error","attr":{"error":1,"message":"[1685027206:939706][1:0x7f90e318fcc0], connection: __posix_open_file, 808: /data/db/WiredTiger.wt: handle-open: open: Operation not permitted"}}
2023-05-25 17:06:46 {"t":{"$date":"2023-05-25T15:06:46.944+00:00"},"s":"W",  "c":"STORAGE",  "id":22347,   "ctx":"initandlisten","msg":"Failed to start up WiredTiger under any compatibility version. This may be due to an unsupported upgrade or downgrade."}
2023-05-25 17:06:46 {"t":{"$date":"2023-05-25T15:06:46.944+00:00"},"s":"F",  "c":"STORAGE",  "id":28595,   "ctx":"initandlisten","msg":"Terminating.","attr":{"reason":"1: Operation not permitted"}}
2023-05-25 17:06:46 {"t":{"$date":"2023-05-25T15:06:46.944+00:00"},"s":"F",  "c":"-",        "id":23091,   "ctx":"initandlisten","msg":"Fatal assertion","attr":{"msgid":28595,"file":"src/mongo/db/storage/wiredtiger/wiredtiger_kv_engine.cpp","line":958}}
2023-05-25 17:06:46 {"t":{"$date":"2023-05-25T15:06:46.944+00:00"},"s":"F",  "c":"-",        "id":23092,   "ctx":"initandlisten","msg":"\n\n***aborting after fassert() failure\n\n"}

**Comment by gereic** [comment]
@ysavary ,

When I want to run without compiling, it won't work.

docker run -it --rm --env-file=.env --network=winds-mobi-providers --volume=$(pwd):/opt/project --entrypoint=python winds.mobi/my_provider -m providers.my_provider

What do I wrong ? I started the command inside the project-directory like the other command.
Do I have to do the build process different maybe ?

**Comment by gereic** [comment]
@ysavary ,
Just another problem, when I want to run it

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/providers/gxaircom.py", line 62, in <module>
    gxaircom()
  File "/providers/gxaircom.py", line 58, in gxaircom
    GxAircom().process_data()
  File "/winds_mobi_provider/provider.py", line 53, in __init__
    self.__stations_collection.create_index(
  File "/.venv/lib/python3.10/site-packages/pymongo/collection.py", line 2048, in create_index
    return self.__create_indexes([index], session, **cmd_options)[0]
  File "/.venv/lib/python3.10/site-packages/pymongo/_csot.py", line 105, in csot_wrapper
    return func(self, *args, **kwargs)
  File "/.venv/lib/python3.10/site-packages/pymongo/collection.py", line 1904, in __create_indexes
    with self._socket_for_writes(session) as sock_info:
  File "/.venv/lib/python3.10/site-packages/pymongo/collection.py", line 241, in _socket_for_writes
    return self.__database.client._socket_for_writes(session)
  File "/.venv/lib/python3.10/site-packages/pymongo/mongo_client.py", line 1239, in _socket_for_writes
    server = self._select_server(writable_server_selector, session)
  File "/.venv/lib/python3.10/site-packages/pymongo/mongo_client.py", line 1229, in _select_server
    server = topology.select_server(server_selector)
  File "/.venv/lib/python3.10/site-packages/pymongo/topology.py", line 272, in select_server
    server = self._select_server(selector, server_selection_timeout, address)
  File "/.venv/lib/python3.10/site-packages/pymongo/topology.py", line 261, in _select_server
    servers = self.select_servers(selector, server_selection_timeout, address)
  File "/.venv/lib/python3.10/site-packages/pymongo/topology.py", line 223, in select_servers
    server_descriptions = self._select_servers_loop(selector, server_timeout, address)
  File "/.venv/lib/python3.10/site-packages/pymongo/topology.py", line 238, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: mongodb:27017: [Errno -3] Temporary failure in name resolution, Timeout: 30s, Topology Description: <TopologyDescription id: 646f8a6bbb30f1cde35ac7d8, topology_type: Unknown, servers: [<ServerDescription ('mongodb', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('mongodb:27017: [Errno -3] Temporary failure in name resolution')>]>

**Comment by ysavary** [comment]
Can you share your docker logs?

**Comment by gereic** [comment]
Seems to work now. Thank you.
